language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: oUUok9/wCihUUVgutUZPlzEZ3AcTP8/d8thqWnlx2TxnKknL6f2C2mYDaEJaVbrLq4WrQOhW6rdXe8btHMV39WEkZAFe1ZSWQL6sPOqkqwHGz5+yOjE8sSZKbSu6ed/C+F81YWmLAi1n4DJ7AXG+BR4vpQDu+ixbnz514fEfiSTq+8Kds5OHUEtTtPTPPyx4LYK6NXY/kqarxTfjwFHLv2EGhhIAtRpo4h83Mh5iOq5Ob6XZafWWvnfeO/b8M1M6ExaTwsglupti0BLUbqYIKrDltvgfS9YNRdiW0h9iViLMcb+MSQfa96ORUwmARj8ZKehyQJkPcvUAI52UpFXMqqEgFighQLG2zOB58nI02/VtxJR2aNSc4+6OrFxJl9UQAxY+gUMTNfps1xXrGZWI/MR3ba/DtrOKmvdKg7SkCvY1hX74z1gOdZjRVztY6b4xY8+/QGTjI67K2Wer/brTDLghdvWhFL14KrWiYaTjthS5spmvb+O7lSovjEUeNlUhr9ChRnmFsBquvD7ezJMPngtG9CigD1zfcluFXPOSvd/0QXMrFM/dJPGmuwSX8UB83W4jEO9B/YRO2G4C9BZdiVJPbLH+0gSEzwEU7qxIOPQ3kwmBFg/VdmWMGk/6OMrn5BVJxBR9NfXn4FCHqVm8AnwM65AimdmsK0Eknl5wTPQ=
  app: accounting-backend-kpociot
  on:
    repo: pociot/accounts
