dist: trusty
sudo: required

language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: pociot-github
    token:
      secure: bonCpuQrlanu0Nto6Z2mXmqF3kbGSO2fifqay5vMngK5exKzopUhjylLFqXoLQ+JXITwaGPqeodYhOFUuEnmZ1G9CO2s7lFP1s3D1FUBbJD2tAJqPAbCGggpQnsyU9SULauOjmPAfgx9RuyOU2tRcS/3CBgwhQTqeygPIHG1xWDuaKpSjlw+mIt+yJK00vaKr3RaenqXbREATHVuv91cQGt++4uyDOxAfLoPKWYOKFeUfdEHNPcEpWooW2Vvf31gesESs4V1ft5JOVjsm3Op07AnETpf0oXmSwBN8/OsdQUIxZ2efeotD9exAFMbK8PI/kCrpfO7cXPCrc/QEGUT5kdLIV4xAhxNCObA7y/zlcmYol75JcgCQFh4dBA2EJkChCBFOt87PYa4C84DtZyvW6p+4kvAhA0JnIwATwzS+klMH5P2Wv5B5KQCD2zsnW8zoaVdyNf3H8ey0YS2A9eXeerSaUhInWU3XTjyXrIGT/wg7ejgfKKFI1NFCqYg/OgC21Nrk/IRlcPVjOz3x3hGNBSyyYP8wEjEsVLH+vZ0QurxMQYpi2VxZzvznOoT9gqJAQ2sK/z5ph7u+UFla6WElOWV91kxqrzd60tdFi9zld+v5r6u6bKNEzuZy+QCMGmHhsYmB8YO0RcBhRUgHBVp0IhPj2Eh3WjYSx31s/v1WLA=

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
  - sonnar-scanner

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

deploy:
  provider: heroku
  api_key:
    secure: oUUok9/wCihUUVgutUZPlzEZ3AcTP8/d8thqWnlx2TxnKknL6f2C2mYDaEJaVbrLq4WrQOhW6rdXe8btHMV39WEkZAFe1ZSWQL6sPOqkqwHGz5+yOjE8sSZKbSu6ed/C+F81YWmLAi1n4DJ7AXG+BR4vpQDu+ixbnz514fEfiSTq+8Kds5OHUEtTtPTPPyx4LYK6NXY/kqarxTfjwFHLv2EGhhIAtRpo4h83Mh5iOq5Ob6XZafWWvnfeO/b8M1M6ExaTwsglupti0BLUbqYIKrDltvgfS9YNRdiW0h9iViLMcb+MSQfa96ORUwmARj8ZKehyQJkPcvUAI52UpFXMqqEgFighQLG2zOB58nI02/VtxJR2aNSc4+6OrFxJl9UQAxY+gUMTNfps1xXrGZWI/MR3ba/DtrOKmvdKg7SkCvY1hX74z1gOdZjRVztY6b4xY8+/QGTjI67K2Wer/brTDLghdvWhFL14KrWiYaTjthS5spmvb+O7lSovjEUeNlUhr9ChRnmFsBquvD7ezJMPngtG9CigD1zfcluFXPOSvd/0QXMrFM/dJPGmuwSX8UB83W4jEO9B/YRO2G4C9BZdiVJPbLH+0gSEzwEU7qxIOPQ3kwmBFg/VdmWMGk/6OMrn5BVJxBR9NfXn4FCHqVm8AnwM65AimdmsK0Eknl5wTPQ=
  app: accounting-backend-kpociot
  on:
    repo: pociot/accounts