dist: trusty
sudo: required

language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: pociot-github
    token:
      secure: bonCpuQrlanu0Nto6Z2mXmqF3kbGSO2fifqay5vMngK5exKzopUhjylLFqXoLQ+JXITwaGPqeodYhOFUuEnmZ1G9CO2s7lFP1s3D1FUBbJD2tAJqPAbCGggpQnsyU9SULauOjmPAfgx9RuyOU2tRcS/3CBgwhQTqeygPIHG1xWDuaKpSjlw+mIt+yJK00vaKr3RaenqXbREATHVuv91cQGt++4uyDOxAfLoPKWYOKFeUfdEHNPcEpWooW2Vvf31gesESs4V1ft5JOVjsm3Op07AnETpf0oXmSwBN8/OsdQUIxZ2efeotD9exAFMbK8PI/kCrpfO7cXPCrc/QEGUT5kdLIV4xAhxNCObA7y/zlcmYol75JcgCQFh4dBA2EJkChCBFOt87PYa4C84DtZyvW6p+4kvAhA0JnIwATwzS+klMH5P2Wv5B5KQCD2zsnW8zoaVdyNf3H8ey0YS2A9eXeerSaUhInWU3XTjyXrIGT/wg7ejgfKKFI1NFCqYg/OgC21Nrk/IRlcPVjOz3x3hGNBSyyYP8wEjEsVLH+vZ0QurxMQYpi2VxZzvznOoT9gqJAQ2sK/z5ph7u+UFla6WElOWV91kxqrzd60tdFi9zld+v5r6u6bKNEzuZy+QCMGmHhsYmB8YO0RcBhRUgHBVp0IhPj2Eh3WjYSx31s/v1WLA=

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
- sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: WyeXB0PF534XnXTeYaKechVUht0MNAbphJKYUGsHVpzOMt+nrWk6suJ8QNCO06XyErfG/qpphFT81cUYMJI7ew8bNMxK6se++zoy4hbOeSt4P/WeVrIC8ZD1cgEGQJ/SJsV8ZLhyiNNw9s8maGW+Su9FJhy7Go1LK5wsvovlp5/bKkcXkhi0BQuwRUwFK/N2OIox6cDA66v5FxCDHkkVxxOxaaJNCe7Iy1gt7l7bCvl7f4zTMLPNpLbYxXzAFKMdVbhXimskSmY9CRdOITheRu7KqPBM97YtbejSa1ZLOL2fRve8OUpeqMl14Wi4hZel+Q/4fBMXorHHE/0XEVJXBNLGI373Z0PanygDru4Cn2xjPlEN1oz/ujLsqC8739K1BxIc/JKTRYz9G12D5dRRiM/XuS3j2vQXTukMcHi67xFVaKt3l7Wpkqk3P+9ECbkjLHyzcLrf5YVa75zddFbxMEnQ95xWitB4MPiaXX4EjMSuN4G1TIzrvWLbdoc+k1ECgAfyO/eXdZc6MCELwyWoAB8X5eQNHdxHmeTgO4Ct2AaukELaZB+f/WEJK6dYUw2I69LL1xopm99aq6Qoxy7s+I8CqUge0DU8qdNfSQnXzIFukgMmAGKPxZic0en3oqbnlin6B1bOZMF3E45Uwa8Zii8Ml+mcF9oGwdqma0NBczU=
  app: hcb-account-service-kpociot
  on:
    repo: pociot/hcb-account-service