eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    statusPageUrl: https://${DOMAIN_NAME}/actuator/info
    healthCheckUrl: https://${DOMAIN_NAME}/actuator/health
    secure-health-check-url: https://${DOMAIN_NAME}/actuator/health
    homePageUrl: https://${DOMAIN_NAME}/
    instance-id: ${DOMAIN_NAME}
  client:
    serviceUrl:
      defaultZone: https://eureka-kpociot.herokuapp.com/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

spring:
  application:
    name: hcb-accounts
