spring:
  application:
    name: hcb-accounts

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    statusPageUrl: https://${eureka.instance.hostName}/info
    healthCheckUrl: https://${eureka.instance.hostName}/health
    homePageUrl: https://${eureka.instance.hostName}/
  client:
    serviceUrl:
      defaultZone: https://eureka-kpociot.herokuapp.com/eureka/