spring:
  application:
    name: hcb-accounts

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    statusPageUrl: https://${DOMAIN_NAME}/info
    healthCheckUrl: https://${DOMAIN_NAME}/health
    homePageUrl: https://${DOMAIN_NAME}/
    metadataMap:
      instanceId: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: https://eureka-kpociot.herokuapp.com/eureka/