spring:
  application:
    name: hcb-accounts

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    secure-port: 443
    secure-port-enabled: true
  client:
    serviceUrl:
      defaultZone: https://eureka-kpociot.herokuapp.com/eureka/