spring:
  application:
    name: hcb-accounts

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: https://eureka-kpociot.herokuapp.com/eureka/