spring:
  application:
    name: hcb-accounts

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    statusPageUrl: https://${DOMAIN_NAME}/info
    healthCheckUrl: https://${DOMAIN_NAME}/health
    homePageUrl: https://${DOMAIN_NAME}/
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: https://eureka-kpociot.herokuapp.com/eureka/